name: CI - Build TIMEGPT.gs

on:
  release:
    types: [published]

jobs:
  build:
    name: Build all-in-one TIMEGPT.gs file
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - name: Build TIMEGPT.gs
        id: build_file
        run: |
          filename=TIMEGPT.gs
          filepath=_build/$filename
          tmpfile=_build/tmp.gs
          mkdir _build
          find . -type f \( -iname "*.gs" ! -iname "config.gs" ! -iname "main.gs" ! -iname "tmp.gs" \) -exec cat > $tmpfile {} +
          cat config.gs > $filepath
          printf "\n\n/////////////////////////////////////\n\n" >> $filepath
          cat main.gs >> $filepath
          printf "\n\n/////////////////////////////////////\n\n" >> $filepath
          cat $tmpfile >> $filepath
          echo "$filename generated!"
          echo "filename=$filename" >> $GITHUB_ENV
          echo "filepath=$filepath" >> $GITHUB_ENV
          echo "filename=$filename" >> $GITHUB_OUTPUT_PATH
          echo "filepath=$filepath" >> $GITHUB_OUTPUT_PATH

      - name: Upload TIMEGPT.gs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.build_file.outputs.filename }}
          path: ${{ steps.build_file.outputs.filepath }}

      - name: Upload appsscript.json as artifact
        uses: actions/upload-artifact@v3
        with:
          name: appsscript.json
          path: appsscript.json

      - name: Release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.build_file.outputs.filepath }}
            appsscript.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}